const DEFAULT_MEALS = [
  {code:'A',day:'Poniedziałek',slot:1,time:'11:00',name:'Owsianka z malinami i odżywką białkową',type:'Śniadanie',tags:['bez gotowania rano','bez laktozy'],ingredients:['płatki owsiane','mleko bez laktozy lub napój roślinny','odżywka białkowa','maliny','orzechy'],steps:['Wieczorem lub rano wsyp płatki do pojemnika.','Dodaj mleko lub napój roślinny oraz odżywkę białkową.','Dodaj maliny i kilka orzechów. Możesz jeść na zimno albo podgrzać w pracy.'],note:'Wybierz odżywkę dobrze tolerowaną jelitowo; przy wrażliwości na laktozę najlepiej bezlaktozową lub roślinną.'},
  {code:'B',day:'Poniedziałek',slot:2,time:'14:00',name:'Schab w sosie pieczarkowym + ziemniaki + marchew',type:'Obiad',tags:['rodzinny','na ciepło','bez laktozy'],ingredients:['schab','pieczarki','cebula','śmietanka owsiana lub sojowa','musztarda','ziemniaki','marchew','olej','sól','pieprz','majeranek'],steps:['Schab pokrój w plastry i krótko obsmaż na niewielkiej ilości oleju.','Zdejmij mięso, wrzuć cebulę i pieczarki.','Dodaj trochę wody, śmietankę roślinną i musztardę.','Włóż schab z powrotem i duś do miękkości.','Podawaj z ziemniakami i gotowaną marchewką.'],note:'Zrób większą porcję schabu — część wykorzystasz w C i E.'},
  {code:'C',day:'Poniedziałek',slot:3,time:'17:30',name:'Sałatka z rukolą, schabem i pomarańczą',type:'Kolacja',tags:['sałatka','wykorzystuje resztki'],ingredients:['rukola','schab z B','pomarańcza','ogórek','pestki dyni','musztarda','sok z cytryny','odrobina oliwy'],steps:['Rukolę przełóż do miski.','Dodaj pokrojony schab, ogórek i cząstki pomarańczy.','Posyp pestkami.','Z musztardy, cytryny, oliwy i odrobiny wody zrób lekki dressing.'],note:'Jeśli pomarańcza lub większa ilość surowych warzyw nasila objawy, zmniejsz porcję.'},
  {code:'D',day:'Wtorek',slot:1,time:'11:00',name:'Kanapki z szynką, jajkiem, szpinakiem i ogórkiem',type:'Śniadanie',tags:['szybkie','do pracy'],ingredients:['pieczywo','lokalna szynka','jajko na twardo','szpinak','ogórek'],steps:['Przygotuj kanapki wieczorem lub rano.','Jajko ugotuj wcześniej i przechowuj w lodówce.'],note:'Bez sosów mlecznych; możesz dodać musztardę.'},
  {code:'E',day:'Wtorek',slot:2,time:'14:00',name:'Schab z sosem cebulowo-musztardowym + miks kasz + buraczki',type:'Obiad',tags:['rodzinny','wykorzystuje B'],ingredients:['schab z B','cebula','musztarda','śmietanka owsiana lub sojowa','miks kasz','buraczki'],steps:['Podgrzej schab.','Cebulę duś na małym ogniu do miękkości.','Dodaj musztardę i śmietankę roślinną.','Podawaj z miksem kasz i buraczkami.'],note:'To samo mięso, ale inny sos — mniej gotowania, inny smak.'},
  {code:'F',day:'Wtorek',slot:3,time:'17:30',name:'Zupa ziemniaczano-koperkowa z indykiem i szpinakiem',type:'Kolacja',tags:['zupa','na ciepło','bez laktozy'],ingredients:['indyk','ziemniaki','marchew','pietruszka korzeń','szpinak','koperek','bulion','śmietanka owsiana'],steps:['Pokrój indyka i warzywa w kostkę.','Gotuj w bulionie do miękkości.','Dodaj szpinak i koperek.','Na końcu dolej śmietankę owsianą i tylko podgrzej.'],note:'Nie miksuj — ma zostać domowa zupa z kawałkami.'},
  {code:'G',day:'Środa',slot:1,time:'11:00',name:'Owsianka z bananem i cynamonem',type:'Śniadanie',tags:['szybkie','do pracy'],ingredients:['płatki owsiane','mleko bez laktozy lub napój roślinny','banan','odżywka białkowa','cynamon'],steps:['Połącz składniki w pojemniku.','Jedz na zimno lub podgrzej w pracy.'],note:'Przy IBS porcję banana dobierz do własnej tolerancji.'},
  {code:'H',day:'Środa',slot:2,time:'14:00',name:'Pulpety z indyka w sosie koperkowym + ziemniaki',type:'Obiad',tags:['rodzinny','na 2 dni'],ingredients:['mielony indyk','jajko','bułka tarta','koperek','bulion','śmietanka owsiana lub sojowa','ziemniaki','marchew lub fasolka szparagowa'],steps:['Wymieszaj mięso, jajko i bułkę tartą.','Uformuj pulpety i duś je w niewielkiej ilości bulionu.','Dodaj śmietankę roślinną i koperek.','Podawaj z ziemniakami i warzywem.'],note:'Zrób więcej pulpetów — przydadzą się do I, K i L.'},
  {code:'I',day:'Środa',slot:3,time:'17:30',name:'Sałatka ze szpinakiem, pulpetami i mango',type:'Kolacja',tags:['sałatka','wykorzystuje H'],ingredients:['szpinak','pulpety z H','mango','ogórek','ugotowana kasza','pestki'],steps:['Połącz szpinak, pokrojone pulpety, ogórek i niewielką porcję mango.','Dodaj trochę ugotowanej kaszy i pestki.','Skrop lekkim dressingiem na bazie cytryny i musztardy.'],note:'Mango ma znaczenie porcjowe przy IBS — zacznij od małej ilości.'},
  {code:'J',day:'Czwartek',slot:1,time:'11:00',name:'Kanapki z szynką, jajkiem i zielonymi dodatkami',type:'Śniadanie',tags:['szybkie','do pracy'],ingredients:['pieczywo','szynka','jajko na twardo','szpinak lub sałata','ogórek'],steps:['Złóż kanapki z przygotowanych składników.'],note:'Proste śniadanie bez smażenia rano.'},
  {code:'K',day:'Czwartek',slot:2,time:'14:00',name:'Pulpety w sosie pomidorowym + makaron',type:'Obiad',tags:['rodzinny','wykorzystuje H'],ingredients:['pulpety z H','passata pomidorowa','makaron','zioła','odrobina oliwy'],steps:['Podgrzej passatę z ziołami.','Dodaj pulpety i duś kilka minut.','Podawaj z makaronem.'],note:'Dla dziecka możesz podać makaron i pulpety z mniejszą ilością sosu.'},
  {code:'L',day:'Czwartek',slot:3,time:'17:30',name:'Zupa pomidorowa z ryżem i małymi pulpecikami',type:'Kolacja',tags:['zupa','na ciepło'],ingredients:['bulion','passata','ryż','małe pulpety z indyka','marchew','śmietanka owsiana opcjonalnie'],steps:['Do bulionu dodaj marchew i ryż.','Dodaj passatę oraz małe pulpety.','Gotuj do miękkości ryżu.','Opcjonalnie zabiel śmietanką roślinną.'],note:'Możesz wykorzystać część pulpetów z H.'},
  {code:'M',day:'Piątek',slot:1,time:'11:00',name:'Owsianka z malinami i jogurtem kokosowym',type:'Śniadanie',tags:['szybkie','bez laktozy'],ingredients:['płatki owsiane','napój roślinny lub mleko bez laktozy','jogurt kokosowy','maliny','odżywka białkowa'],steps:['Połącz płatki z mlekiem lub napojem roślinnym.','Dodaj jogurt kokosowy, maliny i odżywkę.'],note:'Wybieraj jogurt kokosowy o prostym składzie i obserwuj ilość tłuszczu.'},
  {code:'N',day:'Piątek',slot:2,time:'14:00',name:'Pieczona pierś z indyka + ryż/kasza + sos pieczarkowy',type:'Obiad',tags:['rodzinny','meal prep'],ingredients:['pierś z indyka','pieczarki','śmietanka owsiana','ryż lub miks kasz','warzywo gotowane','musztarda','przyprawy'],steps:['Indyka natrzyj przyprawami i piecz do miękkości.','Przygotuj lekki sos pieczarkowy na śmietance owsianej.','Podawaj z ryżem lub kaszą i warzywem.'],note:'Upiecz większy kawałek — wykorzystasz go w O, P i Q.'},
  {code:'O',day:'Piątek',slot:3,time:'17:30',name:'Sałatka z indykiem, pomarańczą i kaszą',type:'Kolacja',tags:['sałatka','wykorzystuje N'],ingredients:['rukola','indyk z N','pomarańcza','kasza lub ryż','ogórek','pestki'],steps:['Połącz rukolę, pokrojonego indyka, pomarańczę, ogórek i kaszę.','Posyp pestkami i dodaj lekki dressing.'],note:'To pełny posiłek, nie dodatek.'},
  {code:'P',day:'Sobota',slot:1,time:'11:00',name:'Kanapki z pieczonym indykiem i warzywami',type:'Śniadanie',tags:['szybkie','wykorzystuje N'],ingredients:['pieczywo','indyk z N','sałata lub szpinak','ogórek','musztarda'],steps:['Złóż kanapki z indykiem i warzywami.'],note:'Możesz zamienić część indyka na lokalną szynkę.'},
  {code:'Q',day:'Sobota',slot:2,time:'14:00',name:'Makaron z indykiem, szpinakiem i śmietanką owsianą',type:'Obiad',tags:['na ciepło','wykorzystuje N'],ingredients:['makaron','indyk z N','szpinak','śmietanka owsiana','musztarda','pieprz'],steps:['Podgrzej indyka na patelni.','Dodaj szpinak i poczekaj aż zwiędnie.','Wlej śmietankę owsianą, dodaj odrobinę musztardy.','Wymieszaj z makaronem.'],note:'Dla dziecka możesz odłożyć makaron i indyka przed dodaniem szpinaku.'},
  {code:'R',day:'Sobota',slot:3,time:'17:30',name:'Zupa warzywna z ziemniakami i drobnym makaronem',type:'Kolacja',tags:['zupa','na ciepło'],ingredients:['ziemniaki','marchew','pietruszka','cukinia opcjonalnie','drobnym makaron','bulion','natka lub koperek'],steps:['Warzywa pokrój w kostkę.','Gotuj w bulionie do miękkości.','Dodaj drobny makaron i gotuj według czasu na opakowaniu.','Dopraw ziołami.'],note:'Bez miksowania i bez ciężkiej śmietany.'},
  {code:'S',day:'Niedziela',slot:1,time:'11:00',name:'Owsianka albo kanapki – zależnie od ochoty',type:'Śniadanie',tags:['elastyczne'],ingredients:['płatki owsiane lub pieczywo','ulubione dodatki z tygodnia'],steps:['Wybierz prostszą opcję na podstawie tego, co zostało w lodówce.'],note:'To celowo elastyczny posiłek „bez marnowania”.'},
  {code:'T',day:'Niedziela',slot:2,time:'14:00',name:'Domowe kotleciki z kurczaka lub ryby + puree + warzywo',type:'Obiad',tags:['rodzinny','dla dziecka'],ingredients:['kurczak lub łagodna ryba','jajko','bułka tarta','ziemniaki','marchew lub buraczki','odrobina oleju'],steps:['Mięso lub rybę drobno posiekaj albo zmiel.','Wymieszaj z jajkiem i bułką tartą.','Uformuj kotleciki i usmaż na niewielkiej ilości tłuszczu lub upiecz.','Podawaj z puree i warzywem.'],note:'Jeśli ryba nie przejdzie, wybierz kurczaka — plan ma być realny.'},
  {code:'U',day:'Niedziela',slot:3,time:'17:30',name:'Sałatka z resztek tygodnia',type:'Kolacja',tags:['zero waste','sałatka'],ingredients:['sałata lub rukola','pozostałe mięso','owoc','ogórek','reszta ryżu lub kaszy','pestki'],steps:['Połącz to, co zostało z tygodnia, w jedną dużą sałatkę.','Dodaj lekki dressing na bazie musztardy i cytryny.'],note:'To specjalny posiłek do opróżniania lodówki przed kolejnym tygodniem.'}
];

const SHOPPING_GROUPS = {
  'Warzywa i owoce':[
    ['rukola / sałata / szpinak','2–3 opakowania łącznie'],['maliny','2 opakowania lub mrożone'],['pomarańcze','3–4 szt.'],['mango','1 szt.'],['ogórki','4–5 szt.'],['marchew','ok. 1 kg'],['ziemniaki','ok. 2,5 kg'],['pieczarki','ok. 700–800 g'],['cebula','4–5 szt.'],['pietruszka korzeń','2 szt.'],['koperek','2 pęczki'],['buraczki','1 opakowanie / słoik o prostym składzie'],['banany','2–3 szt.']
  ],
  'Mięso, jajka i białko':[
    ['schab','ok. 800 g–1 kg'],['indyk mielony','ok. 700–800 g'],['pierś z indyka','ok. 1 kg'],['kurczak lub ryba do kotlecików','ok. 500–600 g'],['lokalna szynka','1 opakowanie / porcja'],['jajka','10 szt.'],['odżywka białkowa','wg zapasu']
  ],
  'Produkty zbożowe':[
    ['płatki owsiane','1 opakowanie'],['pieczywo','wg potrzeb'],['makaron','2 opakowania'],['ryż','1 opakowanie'],['miks kasz / kasza gryczana','2–3 opakowania'],['bułka tarta','1 opakowanie']
  ],
  'Roślinne i bez laktozy':[
    ['mleko bez laktozy lub napój roślinny','2–3 l'],['śmietanka owsiana/sojowa do gotowania','3–4 opakowania'],['jogurt kokosowy','1 opakowanie']
  ],
  'Spiżarnia':[
    ['musztarda','1 słoik'],['passata pomidorowa','2 butelki/kartony'],['bulion / składniki na bulion','wg zapasu'],['pestki dyni','1 opakowanie'],['orzechy','1 małe opakowanie'],['oliwa / olej','wg zapasu'],['cynamon, majeranek, pieprz, zioła','wg zapasu']
  ]
};

const USE_UP = [
  {name:'Szpinak',text:'D, F, I, J i Q — kup 1–2 opakowania i zużywaj po kolei między kanapkami, zupą, sałatką i makaronem.'},
  {name:'Schab',text:'B → C → E. Jedno pieczenie / duszenie daje obiad, sałatkę i drugi obiad z innym sosem.'},
  {name:'Pulpety z indyka',text:'H → I → K → L. Zrób większą porcję, a potem zmieniaj formę podania.'},
  {name:'Pieczony indyk',text:'N → O → P → Q. To główny meal prep na koniec tygodnia.'},
  {name:'Pomarańcze',text:'C i O. Jeśli zostanie owoc, dodaj go do S lub U.'},
  {name:'Śmietanka roślinna',text:'B, E, F, H, L, N i Q. Otwieraj jedno opakowanie i planuj zużyć je w 2–3 daniach.'}
];
