const DEFAULT_MEALS = [
  {code:'A',day:'Poniedziałek',slot:1,time:'11:00',name:'Owsianka z malinami i odżywką białkową',type:'Śniadanie',tags:['szybkie','bez laktozy'],nutrition:{kcal:525,protein:35,carbs:61,fat:16},ingredients:['płatki owsiane – 60 g','mleko bez laktozy lub napój sojowy – 200 ml','odżywka białkowa – 25 g','maliny – 100 g','orzechy włoskie – 10 g'],steps:['Połącz płatki z mlekiem lub napojem roślinnym.','Dodaj odżywkę białkową, maliny i orzechy.','Możesz przygotować wieczorem i podgrzać w pracy.'],note:'Gramatury dotyczą Twojej porcji. Wartości odżywcze są orientacyjne i zależą od marki produktów.'},
  {code:'B',day:'Poniedziałek',slot:2,time:'14:00',name:'Schab w sosie pieczarkowym + ziemniaki + marchew',type:'Obiad',tags:['rodzinny','na ciepło','bez laktozy'],nutrition:{kcal:740,protein:49,carbs:78,fat:25},ingredients:['schab – 170 g','ziemniaki – 300 g','marchew – 150 g','pieczarki – 150 g','cebula – 50 g','śmietanka owsiana/sojowa – 80 ml','musztarda – 10 g','olej – 5 g','sól, pieprz, majeranek – do smaku'],steps:['Schab pokrój w plastry i krótko obsmaż na oleju.','Zdejmij mięso, wrzuć cebulę i pieczarki.','Dodaj trochę wody, śmietankę roślinną i musztardę.','Włóż schab z powrotem i duś do miękkości.','Podawaj z ziemniakami i gotowaną marchewką.'],note:'Zrób większą porcję schabu — część wykorzystasz w C i E.'},
  {code:'C',day:'Poniedziałek',slot:3,time:'17:30',name:'Sałatka z rukolą, schabem i pomarańczą',type:'Kolacja',tags:['sałatka','wykorzystuje B'],nutrition:{kcal:545,protein:34,carbs:50,fat:23},ingredients:['rukola – 50 g','schab z B – 120 g','pomarańcza – 150 g','ogórek – 150 g','ugotowana kasza – 100 g','pestki dyni – 15 g','oliwa – 5 g','musztarda + sok z cytryny – 10–15 g'],steps:['Rukolę przełóż do miski.','Dodaj pokrojony schab, ogórek, pomarańczę i kaszę.','Posyp pestkami.','Z musztardy, cytryny, oliwy i odrobiny wody zrób lekki dressing.'],note:'Jeśli większa ilość surowych warzyw nasila IBS, zmniejsz ogórek lub rukolę.'},
  {code:'D',day:'Wtorek',slot:1,time:'11:00',name:'Kanapki z szynką, jajkiem, szpinakiem i ogórkiem',type:'Śniadanie',tags:['szybkie','do pracy'],nutrition:{kcal:505,protein:31,carbs:59,fat:16},ingredients:['pieczywo – 120 g','lokalna szynka – 80 g','jajko na twardo – 1 szt.','szpinak – 30 g','ogórek – 100 g','musztarda – 10 g'],steps:['Przygotuj kanapki wieczorem lub rano.','Jajko ugotuj wcześniej i przechowuj w lodówce.'],note:'Bez sosów mlecznych; musztarda wystarczy jako dodatek.'},
  {code:'E',day:'Wtorek',slot:2,time:'14:00',name:'Schab z sosem cebulowo-musztardowym + miks kasz + buraczki',type:'Obiad',tags:['rodzinny','wykorzystuje B'],nutrition:{kcal:755,protein:46,carbs:86,fat:25},ingredients:['schab z B – 160 g','ugotowany miks kasz – 250 g','buraczki – 150 g','cebula – 70 g','śmietanka owsiana/sojowa – 70 ml','musztarda – 10 g','olej – 5 g'],steps:['Podgrzej schab.','Cebulę duś na małym ogniu do miękkości.','Dodaj musztardę i śmietankę roślinną.','Podawaj z miksem kasz i buraczkami.'],note:'To samo mięso, ale inny sos — mniej gotowania, inny smak.'},
  {code:'F',day:'Wtorek',slot:3,time:'17:30',name:'Zupa ziemniaczano-koperkowa z indykiem i szpinakiem',type:'Kolacja',tags:['zupa','na ciepło','bez laktozy'],nutrition:{kcal:540,protein:42,carbs:62,fat:15},ingredients:['pierś z indyka – 150 g','ziemniaki – 250 g','marchew – 100 g','pietruszka korzeń – 50 g','szpinak – 50 g','śmietanka owsiana – 60 ml','bulion – 300 ml','koperek – 10 g'],steps:['Pokrój indyka i warzywa w kostkę.','Gotuj w bulionie do miękkości.','Dodaj szpinak i koperek.','Na końcu dolej śmietankę owsianą i tylko podgrzej.'],note:'Nie miksuj — ma zostać domowa zupa z kawałkami.'},
  {code:'G',day:'Środa',slot:1,time:'11:00',name:'Owsianka z bananem i cynamonem',type:'Śniadanie',tags:['szybkie','do pracy'],nutrition:{kcal:510,protein:34,carbs:72,fat:10},ingredients:['płatki owsiane – 60 g','mleko bez laktozy lub napój sojowy – 200 ml','banan – 100 g','odżywka białkowa – 25 g','cynamon – do smaku'],steps:['Połącz składniki w pojemniku.','Jedz na zimno lub podgrzej w pracy.'],note:'Przy IBS porcję banana dobierz do własnej tolerancji.'},
  {code:'H',day:'Środa',slot:2,time:'14:00',name:'Pulpety z indyka w sosie koperkowym + ziemniaki',type:'Obiad',tags:['rodzinny','na 2 dni'],nutrition:{kcal:750,protein:50,carbs:77,fat:27},ingredients:['mielony indyk – 180 g','jajko – 1/2 szt.','bułka tarta – 20 g','ziemniaki – 300 g','marchew lub fasolka szparagowa – 150 g','śmietanka owsiana/sojowa – 70 ml','bulion – 100 ml','koperek – 10 g','olej – 5 g'],steps:['Wymieszaj mięso, jajko i bułkę tartą.','Uformuj pulpety i duś je w niewielkiej ilości bulionu.','Dodaj śmietankę roślinną i koperek.','Podawaj z ziemniakami i warzywem.'],note:'Zrób więcej pulpetów — przydadzą się do I, K i L.'},
  {code:'I',day:'Środa',slot:3,time:'17:30',name:'Sałatka ze szpinakiem, pulpetami i mango',type:'Kolacja',tags:['sałatka','wykorzystuje H'],nutrition:{kcal:540,protein:32,carbs:50,fat:24},ingredients:['szpinak – 50 g','pulpety z H – 130 g','mango – 80 g','ogórek – 150 g','ugotowana kasza – 100 g','pestki dyni – 15 g','oliwa – 5 g'],steps:['Połącz szpinak, pokrojone pulpety, ogórek i mango.','Dodaj kaszę i pestki.','Skrop lekkim dressingiem na bazie cytryny i musztardy.'],note:'Mango ma znaczenie porcjowe przy IBS — zacznij od tej małej ilości.'},
  {code:'J',day:'Czwartek',slot:1,time:'11:00',name:'Kanapki z szynką, jajkiem i zielonymi dodatkami',type:'Śniadanie',tags:['szybkie','do pracy'],nutrition:{kcal:500,protein:31,carbs:58,fat:16},ingredients:['pieczywo – 120 g','szynka – 80 g','jajko na twardo – 1 szt.','szpinak lub sałata – 30 g','ogórek – 100 g','musztarda – 10 g'],steps:['Złóż kanapki z przygotowanych składników.'],note:'Proste śniadanie bez smażenia rano.'},
  {code:'K',day:'Czwartek',slot:2,time:'14:00',name:'Pulpety w sosie pomidorowym + makaron',type:'Obiad',tags:['rodzinny','wykorzystuje H'],nutrition:{kcal:755,protein:46,carbs:93,fat:22},ingredients:['pulpety z H – 200 g','makaron suchy – 100 g','passata pomidorowa – 200 g','oliwa – 5 g','zioła – do smaku'],steps:['Podgrzej passatę z ziołami.','Dodaj pulpety i duś kilka minut.','Podawaj z makaronem.'],note:'Dla dziecka możesz podać makaron i pulpety z mniejszą ilością sosu.'},
  {code:'L',day:'Czwartek',slot:3,time:'17:30',name:'Zupa pomidorowa z ryżem i małymi pulpecikami',type:'Kolacja',tags:['zupa','na ciepło'],nutrition:{kcal:545,protein:31,carbs:67,fat:17},ingredients:['małe pulpety z indyka – 120 g','ryż suchy – 60 g','passata – 200 g','marchew – 100 g','bulion – 300 ml','śmietanka owsiana – 40 ml'],steps:['Do bulionu dodaj marchew i ryż.','Dodaj passatę oraz małe pulpety.','Gotuj do miękkości ryżu.','Na końcu opcjonalnie dodaj śmietankę roślinną.'],note:'Możesz wykorzystać część pulpetów z H.'},
  {code:'M',day:'Piątek',slot:1,time:'11:00',name:'Owsianka z malinami i jogurtem kokosowym',type:'Śniadanie',tags:['szybkie','bez laktozy'],nutrition:{kcal:535,protein:32,carbs:59,fat:20},ingredients:['płatki owsiane – 55 g','mleko bez laktozy lub napój sojowy – 200 ml','jogurt kokosowy – 80 g','maliny – 100 g','odżywka białkowa – 25 g'],steps:['Połącz płatki z mlekiem lub napojem roślinnym.','Dodaj jogurt kokosowy, maliny i odżywkę.'],note:'Jogurty kokosowe mocno różnią się kalorycznością — sprawdź etykietę swojego.'},
  {code:'N',day:'Piątek',slot:2,time:'14:00',name:'Pieczona pierś z indyka + ryż/kasza + sos pieczarkowy',type:'Obiad',tags:['rodzinny','meal prep'],nutrition:{kcal:750,protein:55,carbs:79,fat:23},ingredients:['pierś z indyka – 180 g','ryż suchy lub kasza – 80 g','pieczarki – 150 g','śmietanka owsiana – 70 ml','warzywo gotowane – 200 g','musztarda – 10 g','olej – 5 g','przyprawy – do smaku'],steps:['Indyka natrzyj przyprawami i piecz do miękkości.','Przygotuj lekki sos pieczarkowy na śmietance owsianej.','Podawaj z ryżem lub kaszą i warzywem.'],note:'Upiecz większy kawałek — wykorzystasz go w O, P i Q.'},
  {code:'O',day:'Piątek',slot:3,time:'17:30',name:'Sałatka z indykiem, pomarańczą i kaszą',type:'Kolacja',tags:['sałatka','wykorzystuje N'],nutrition:{kcal:570,protein:39,carbs:54,fat:23},ingredients:['rukola – 50 g','indyk z N – 140 g','pomarańcza – 150 g','ugotowana kasza lub ryż – 150 g','ogórek – 150 g','pestki dyni – 15 g','oliwa – 5 g'],steps:['Połącz rukolę, pokrojonego indyka, pomarańczę, ogórek i kaszę.','Posyp pestkami i dodaj lekki dressing.'],note:'To pełny posiłek, nie dodatek.'},
  {code:'P',day:'Sobota',slot:1,time:'11:00',name:'Kanapki z pieczonym indykiem i warzywami',type:'Śniadanie',tags:['szybkie','wykorzystuje N'],nutrition:{kcal:495,protein:38,carbs:56,fat:14},ingredients:['pieczywo – 120 g','indyk z N – 120 g','sałata lub szpinak – 30 g','ogórek – 100 g','musztarda – 10 g'],steps:['Złóż kanapki z indykiem i warzywami.'],note:'Możesz zamienić część indyka na lokalną szynkę.'},
  {code:'Q',day:'Sobota',slot:2,time:'14:00',name:'Makaron z indykiem, szpinakiem i śmietanką owsianą',type:'Obiad',tags:['na ciepło','wykorzystuje N'],nutrition:{kcal:725,protein:51,carbs:88,fat:20},ingredients:['makaron suchy – 90 g','indyk z N – 150 g','szpinak – 80 g','śmietanka owsiana – 100 ml','musztarda – 10 g','pieprz – do smaku'],steps:['Podgrzej indyka na patelni.','Dodaj szpinak i poczekaj aż zwiędnie.','Wlej śmietankę owsianą i dodaj musztardę.','Wymieszaj z makaronem.'],note:'Dla dziecka możesz odłożyć makaron i indyka przed dodaniem szpinaku.'},
  {code:'R',day:'Sobota',slot:3,time:'17:30',name:'Zupa warzywna z ziemniakami i drobnym makaronem',type:'Kolacja',tags:['zupa','na ciepło'],nutrition:{kcal:555,protein:22,carbs:88,fat:12},ingredients:['ziemniaki – 250 g','drobnym makaron suchy – 50 g','marchew – 100 g','pietruszka korzeń – 50 g','cukinia – 100 g','bulion – 350 ml','pieczywo – 50 g','natka lub koperek – do smaku'],steps:['Warzywa pokrój w kostkę.','Gotuj w bulionie do miękkości.','Dodaj drobny makaron i gotuj według czasu na opakowaniu.','Podawaj z kromką pieczywa.'],note:'Jeśli po tej kolacji będziesz szybko głodna, następnym razem dodamy do zupy mięso lub jajko na twardo.'},
  {code:'S',day:'Niedziela',slot:1,time:'11:00',name:'Kanapki z szynką, jajkiem i warzywami',type:'Śniadanie',tags:['proste','bez gotowania rano'],nutrition:{kcal:505,protein:31,carbs:59,fat:16},ingredients:['pieczywo – 120 g','lokalna szynka – 80 g','jajko na twardo – 1 szt.','sałata lub szpinak – 30 g','ogórek – 100 g','musztarda – 10 g'],steps:['Złóż kanapki z przygotowanych składników.'],note:'W niedzielę możesz zamienić ten posiłek na owsiankę A lub G o podobnej kaloryczności.'},
  {code:'T',day:'Niedziela',slot:2,time:'14:00',name:'Domowe kotleciki z kurczaka lub ryby + puree + warzywo',type:'Obiad',tags:['rodzinny','dla dziecka'],nutrition:{kcal:745,protein:49,carbs:75,fat:28},ingredients:['kurczak lub łagodna ryba – 180 g','jajko – 1/2 szt.','bułka tarta – 20 g','ziemniaki – 300 g','marchew lub buraczki – 180 g','olej – 10 g'],steps:['Mięso lub rybę drobno posiekaj albo zmiel.','Wymieszaj z jajkiem i bułką tartą.','Uformuj kotleciki i usmaż na niewielkiej ilości tłuszczu lub upiecz.','Podawaj z puree i warzywem.'],note:'Jeśli ryba nie przejdzie, wybierz kurczaka — plan ma być realny.'},
  {code:'U',day:'Niedziela',slot:3,time:'17:30',name:'Sałatka z resztek tygodnia – wersja z gramaturą',type:'Kolacja',tags:['zero waste','sałatka'],nutrition:{kcal:545,protein:37,carbs:49,fat:22},ingredients:['sałata lub rukola – 60 g','pozostałe mięso – 130 g','owoc – 100 g','ogórek – 150 g','ugotowany ryż lub kasza – 150 g','pestki – 15 g','oliwa – 5 g'],steps:['Odważ składniki według podanej gramatury.','Połącz wszystko w dużą sałatkę.','Dodaj lekki dressing na bazie musztardy i cytryny.'],note:'Możesz zmieniać rodzaj mięsa, owocu i kaszy, ale zachowaj podobne gramatury, żeby kaloryczność była zbliżona.'}
];

const SHOPPING_GROUPS = {
  'Warzywa i owoce':[
    ['rukola / sałata / szpinak','2–3 opakowania łącznie'],['maliny','2 opakowania lub mrożone'],['pomarańcze','3–4 szt.'],['mango','1 szt.'],['ogórki','4–5 szt.'],['marchew','ok. 1 kg'],['ziemniaki','ok. 2,5 kg'],['pieczarki','ok. 700–800 g'],['cebula','4–5 szt.'],['pietruszka korzeń','2 szt.'],['koperek','2 pęczki'],['buraczki','1 opakowanie / słoik o prostym składzie'],['banany','2–3 szt.']
  ],
  'Mięso, jajka i białko':[
    ['schab','ok. 800 g–1 kg'],['indyk mielony','ok. 700–800 g'],['pierś z indyka','ok. 1 kg'],['kurczak lub ryba do kotlecików','ok. 500–600 g'],['lokalna szynka','1 opakowanie / porcja'],['jajka','10 szt.'],['odżywka białkowa','wg zapasu']
  ],
  'Produkty zbożowe':[
    ['płatki owsiane','1 opakowanie'],['pieczywo','wg potrzeb'],['makaron','2 opakowania'],['ryż','1 opakowanie'],['miks kasz / kasza gryczana','2–3 opakowania'],['bułka tarta','1 opakowanie']
  ],
  'Roślinne i bez laktozy':[
    ['mleko bez laktozy lub napój roślinny','2–3 l'],['śmietanka owsiana/sojowa do gotowania','3–4 opakowania'],['jogurt kokosowy','1 opakowanie']
  ],
  'Spiżarnia':[
    ['musztarda','1 słoik'],['passata pomidorowa','2 butelki/kartony'],['bulion / składniki na bulion','wg zapasu'],['pestki dyni','1 opakowanie'],['orzechy','1 małe opakowanie'],['oliwa / olej','wg zapasu'],['cynamon, majeranek, pieprz, zioła','wg zapasu']
  ]
};

const USE_UP = [
  {name:'Szpinak',text:'D, F, I, J i Q — kup 1–2 opakowania i zużywaj po kolei między kanapkami, zupą, sałatką i makaronem.'},
  {name:'Schab',text:'B → C → E. Jedno pieczenie / duszenie daje obiad, sałatkę i drugi obiad z innym sosem.'},
  {name:'Pulpety z indyka',text:'H → I → K → L. Zrób większą porcję, a potem zmieniaj formę podania.'},
  {name:'Pieczony indyk',text:'N → O → P → Q. To główny meal prep na koniec tygodnia.'},
  {name:'Pomarańcze',text:'C i O. Jeśli zostanie owoc, dodaj go do S lub U.'},
  {name:'Śmietanka roślinna',text:'B, E, F, H, L, N i Q. Otwieraj jedno opakowanie i planuj zużyć je w 2–3 daniach.'}
];
